language: node_js

node_js:
  - "9.8"

script:
  - npm run test
  - npm run build

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: dist
    on:
      branch: master

  - provider: script
    skip-cleanup: true
    script: npm run deploy
    on:
      branch: master

notifications:
  email: false
